version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fun_game_user:xOuZ6LLpXDxBGg9WnSRalfc1H1dRAqj6@dpg-ctgsn00gph6c73ckd45g-a.singapore-postgres.render.com/fun_game
      - SECRET_KEY=d6A9bE3cAf2D6E5d8eFb6d8A6Bc9D1d5F7A2
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30